### ISSUE TITLE
Unable to load jackett container

### ISSUE THREAD

**Issue by CraftyClown** [hotio/docker-jackett#3]
Hi hotio,

firstly apologies as I am new to docker, so it may be that I am doing something stupid, but I'm struggling to get your Jackett container working.

I already have your Radarr, Sonarr and Lidarr containers up and functioning, but for some reason Jackett just doesn't want to play ball.

I'm running all of them as service scripts so they start at system boot and this is the script I'm using for Jackett:

```
[Unit]
Description=jackett docker container
Requires=docker.service
After=docker.service
[Service]
Restart=always
RestartSec=30
ExecStart=/usr/bin/docker run --rm \
                              --name=jackett \
                              -e PUID=1000 \
                              -e PGID=1000 \
                              -e TZ=Europe/London \
                              -e UMASK=002 \
                              -v /home/craftyclown/.config/Docker/Jackett:/config \
                              -p 9117:9117 \
                              hotio/jackett
ExecStop=/usr/bin/docker stop jackett
[Install]
WantedBy=multi-user.target
```
Do you see anything odd about the way I'm calling it?

If I run docker ps I only see Radarr, Lidarr, Sonarr and Portainer running

**Comment by hotio** [comment]
At first glance it looks good to me, could you try adding `-e DEBUG=yes` and than show the output of `docker logs jackett`...
